// #define bme280123 //COMMENT OUT for bme680. DEFINE for 280
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"
#include "sdkconfig.h" // generated by "make menuconfig"
#include "bme280.h"
#include "bme680.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "freertos/queue.h"
#include "connect.h"
//#include "esp_event_loop.h"
#include "esp_event.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "cJSON.h"
#include "mqtt_client.h"
#include "pms5003.h"
#include "esp_system.h"
#include "esp_attr.h"
#include "esp_sleep.h"
#include "C:\Users\Timot\esp\esp-idf\examples\common_components\protocol_examples_common\include\protocol_examples_common.h"
#include "esp_sntp.h"
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_attr.h"
#include "esp_sleep.h"
#include "nvs_flash.h"

//280 pins def
#define SDA_PIN 8
#define SCL_PIN 9



#define uart_set_baud(p,r)  uart_set_baudrate (p,r)

#define TAG_BME280 "BME280"

#define I2C_MASTER_ACK 0
#define I2C_MASTER_NACK 1
#define I2C_BUS       0
// 680 pins def
#define I2C_SDA_PIN   19
#define I2C_SCL_PIN   20
#define i2c_280 1
#define I2C_FREQ      I2C_FREQ_100K

#define TAG1 "MQTT"
#define TAG2 "SNTP"


void i2c_master_init()
{
	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(i2c_280, &i2c_config);
	i2c_driver_install(i2c_280, I2C_MODE_MASTER, 0, 0, 0);
}

s8 BME280_I2C_bus_write(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
{
	s32 iError = BME280_INIT_VALUE;

	esp_err_t espRc;
	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, reg_addr, true);
	i2c_master_write(cmd, reg_data, cnt, true);
	i2c_master_stop(cmd);

	espRc = i2c_master_cmd_begin(i2c_280, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		iError = SUCCESS;
	} else {
		iError = FAIL;
	}
	i2c_cmd_link_delete(cmd);

	return (s8)iError;
}

s8 BME280_I2C_bus_read(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
{
	s32 iError = BME280_INIT_VALUE;
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, reg_addr, true);

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_READ, true);

	if (cnt > 1) {
		i2c_master_read(cmd, reg_data, cnt-1, I2C_MASTER_ACK);
	}
	i2c_master_read_byte(cmd, reg_data+cnt-1, I2C_MASTER_NACK);
	i2c_master_stop(cmd);

	espRc = i2c_master_cmd_begin(i2c_280, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		iError = SUCCESS;
	} else {
		iError = FAIL;
	}

	i2c_cmd_link_delete(cmd);

	return (s8)iError;
}

void BME280_delay_msek(u32 msek)
{
	vTaskDelay(msek/portTICK_PERIOD_MS);
}

static void obtain_time(void);
static void initialize_sntp(void);

static void obtain_time(void)
{
    ESP_ERROR_CHECK( nvs_flash_init() );
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK( esp_event_loop_create_default() );

    /**
     * NTP server address could be aquired via DHCP,
     * see LWIP_DHCP_GET_NTP_SRV menuconfig option
     */
#ifdef LWIP_DHCP_GET_NTP_SRV
    sntp_servermode_dhcp(1);
#endif

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());

    initialize_sntp();

    // wait for time to be set
    time_t now = 0;
    struct tm timeinfo = { 0 };
    int retry = 0;
    const int retry_count = 10;
    while (sntp_get_sync_status() == SNTP_SYNC_STATUS_RESET && ++retry < retry_count) {
        ESP_LOGI("", "Waiting for system time to be set... (%d/%d)", retry, retry_count);
        vTaskDelay(2000 / portTICK_PERIOD_MS);
    }
    time(&now);
    localtime_r(&now, &timeinfo);

    ESP_ERROR_CHECK( example_disconnect() );
}

void time_sync_notification_cb(struct timeval *tv)
{
    ESP_LOGI("", "Notification of a time synchronization event");
}

static void initialize_sntp(void)
{
    ESP_LOGI("", "Initializing SNTP");
    sntp_setoperatingmode(SNTP_OPMODE_POLL);
    sntp_setservername(0, "pool.ntp.org");
    sntp_set_time_sync_notification_cb(time_sync_notification_cb);
    sntp_init();
}

void app_main(void)
{
  // fieldnames = ["PM1", "PM2", "PM3", "Temp", "Humid", "Press", "Resist", "Time"]

  #ifdef bme280123

    time_t now;
    struct tm timeinfo;
    i2c_master_init(); 
    struct bme280_t bme280 = {
      .bus_write = BME280_I2C_bus_write,
      .bus_read = BME280_I2C_bus_read,
      .dev_addr = BME280_I2C_ADDRESS2,
      .delay_msec = BME280_delay_msek
    };
    s32 com_rslt;
    s32 v_uncomp_pressure_s32;
    s32 v_uncomp_temperature_s32;
    s32 v_uncomp_humidity_s32;
    com_rslt = bme280_init(&bme280);
    com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_16X);
    com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_2X);
    com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);
    com_rslt += bme280_set_standby_durn(BME280_STANDBY_TIME_1_MS);
    com_rslt += bme280_set_filter(BME280_FILTER_COEFF_16);
    com_rslt += bme280_set_power_mode(BME280_NORMAL_MODE);   

    pms5003_config_t pms0 = {
            .set_pin = GPIO_NUM_13,
            .reset_pin = GPIO_NUM_27,
            .mode_pin = GPIO_NUM_26,
            .rxd_pin = GPIO_NUM_14,
            .txd_pin = GPIO_NUM_15,
            .uart_instance = UART_NUM_1,
            .uart_buffer_size = 128
    };
    pms5003_setup(&pms0);
    pms5003_measurement_t reading;
	  if (com_rslt == SUCCESS) { //possibly eliminate
      while(true) {
        // time stuff  
          vTaskDelay(1000/portTICK_PERIOD_MS);
        time(&now);
        localtime_r(&now, &timeinfo);
        if (timeinfo.tm_year < (2016 - 1900)) {
            obtain_time();
            // update 'now' variable with current time
            time(&now);
        }
        char strftime_buf[64];
        setenv("TZ", "PST8PDT,M3.2.0/2,M11.1.0", 1);tzset();localtime_r(&now, &timeinfo);strftime(strftime_buf, sizeof(strftime_buf), "%c", &timeinfo);    
        char buffer2[600];
        char buffer3[1000];
        com_rslt = bme280_read_uncomp_pressure_temperature_humidity(
        &v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);
        pms5003_make_measurement(&pms0, &reading);
        // fieldnames = ["PM1", "PM2", "PM3", "Temp", "Humid", "Press", "Resist", "Time"]
        if (com_rslt == SUCCESS) {
          printf("%d, %d, %d, %.2f,%.3f,%.3f,%.3f, %s \n", reading.pm1_0_std,reading.pm2_5_std,reading.pm10_std,
          bme280_compensate_temperature_double(v_uncomp_temperature_s32), bme280_compensate_humidity_double(v_uncomp_humidity_s32),
          bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100,bme280_compensate_temperature_double(v_uncomp_temperature_s32) ,strftime_buf);
          // added a duplicate temperature to take the place of temperature
          // sprintf(buffer3,"%s,%d,%d,%d,%s","Node1", 123, 123, 123, buffer2);
          // printf("Sensors Generated: %s\n", buffer3);
        } 
      }
	}
  #else /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //280 stuff
  i2c_master_init(); 
    struct bme280_t bme280 = {
      .bus_write = BME280_I2C_bus_write,
      .bus_read = BME280_I2C_bus_read,
      .dev_addr = BME280_I2C_ADDRESS2,
      .delay_msec = BME280_delay_msek
    };
  s32 com_rslt;
  s32 v_uncomp_pressure_s32;
  s32 v_uncomp_temperature_s32;
  s32 v_uncomp_humidity_s32;
  com_rslt = bme280_init(&bme280);
  com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_16X);
  com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_2X);
  com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);
  com_rslt += bme280_set_standby_durn(BME280_STANDBY_TIME_1_MS);
  com_rslt += bme280_set_filter(BME280_FILTER_COEFF_16);
  com_rslt += bme280_set_power_mode(BME280_NORMAL_MODE);
  //680 stuff
  bme680_sensor_t* sensor = 0;
  i2c_init(0, I2C_SCL_PIN, I2C_SDA_PIN, I2C_FREQ);
  sensor = bme680_init_sensor (I2C_BUS, BME680_I2C_ADDRESS_2, 0);
  bme680_set_oversampling_rates(sensor, osr_4x, osr_2x, osr_2x);
  bme680_set_filter_size(sensor, iir_size_7);
  bme680_set_heater_profile (sensor, 0, 200, 100);
  bme680_use_heater_profile (sensor, 0);
  bme680_set_ambient_temperature (sensor, 25);
  bme680_values_float_t values;
  uint32_t duration = bme680_get_measurement_duration(sensor);
  pms5003_measurement_t reading;
  pms5003_config_t pms0 = {
              .set_pin = GPIO_NUM_13,
              .reset_pin = GPIO_NUM_27,
              .mode_pin = GPIO_NUM_26,
              .rxd_pin = GPIO_NUM_14,
              .txd_pin = GPIO_NUM_15,
              .uart_instance = UART_NUM_1,
              .uart_buffer_size = 128
      };
  pms5003_setup(&pms0);
  
  while (1){
    // fieldnames = ["PM1", "PM2", "PM3", "Temp", "Humid", "Press", "Resist", "Time"]
    
    vTaskDelay(1000/portTICK_RATE_MS);
    
    if (bme680_force_measurement(sensor)){
      pms5003_make_measurement(&pms0, &reading);

      bme280_read_uncomp_pressure_temperature_humidity(
      &v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);
      vTaskDelay (duration);
      if (bme680_get_results_float (sensor, &values)){
        printf("%d, %d, %d, %.2f °C, %.2f %%, %.2f hPa, %.2f Ohm,%.2f,%.3f,%.3f\n",
        reading.pm1_0_std, reading.pm2_5_std, reading.pm10_std, 
        values.temperature, values.humidity, values.pressure, values.gas_resistance, bme280_compensate_temperature_double(v_uncomp_temperature_s32), bme280_compensate_humidity_double(v_uncomp_humidity_s32),
          bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100);
      }

    }
  }
  #endif
}  




